spring:
  application:
    name: ${SPRING_APPLICATION_NAME_GATEWAY}
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_HTTP_PORT}
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
      config:
        enabled: false # Disable Consul Config if not using centralized configuration
        format: yaml
        default-context: application
        profile-separator: "-"
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowed-origins: "${GATEWAY_ALLOWED_ORIGINS}"
            allowed-methods: "${GATEWAY_ALLOWED_METHODS}"
            allowed-headers: "${GATEWAY_ALLOWED_HEADERS}"
            allow-credentials: true
            max-age: ${GATEWAY_CORS_MAX_AGE}

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: ${GATEWAY_SERVICE_PORT}