spring:
  config:
    activate:
      on-profile:
      - dev
  application:
    name: ${SPRING_APPLICATION_NAME_GATEWAY}
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowed-origins: "${GATEWAY_ALLOWED_ORIGINS}"
            allowed-methods: "${GATEWAY_ALLOWED_METHODS}"
            allowed-headers: "${GATEWAY_ALLOWED_HEADERS}"
            allow-credentials: true
            max-age: ${GATEWAY_CORS_MAX_AGE}

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: ${GATEWAY_SERVICE_PORT}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka/
    register-with-eureka: true
    fetch-registry: true