services:
  mysql:
    profiles: ["infra", "dev"]
    image: mysql:latest
    container_name: devops-ms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - devops-ms-mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${MYSQL_PORT}:${MYSQL_INTERNAL_PORT}"
    networks:
      - devops-ms-net
  consul:
    profiles: ["infra", "dev"]
    container_name: devops-ms-consul
    image: consul:1.15.4
    command: agent -server -bootstrap-expect=1 -ui -client=${CONSUL_CLIENT}
    ports:
      - "${CONSUL_HTTP_PORT}:8500"
      - "${CONSUL_DNS_PORT}:8600/udp"
    environment:
      CONSUL_BIND_INTERFACE: ${CONSUL_BIND_INTERFACE}
      CONSUL_LOG_LEVEL: ${CONSUL_LOG_LEVEL}
      CONSUL_NODE_ROLE: ${CONSUL_NODE_ROLE}
      CONSUL_DATACENTER: ${CONSUL_DATACENTER}
      CONSUL_ENCRYPT: ${CONSUL_ENCRYPT_KEY}
    volumes:
      - devops-ms-consul:/consul/data
    networks:
      - devops-ms-net
    restart: unless-stopped
  client-service:
    profiles: ["dev"]
    build:
      context: ../client
      dockerfile: Dockerfile
    container_name: devops-ms-client-service
    ports:
      - "${CLIENT_SERVICE_PORT}:${CLIENT_SERVICE_PORT}"
    networks:
      - devops-ms-net
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CLIENT_SERVICE_PORT: ${CLIENT_SERVICE_PORT}
      SPRING_APPLICATION_NAME_CLIENT: ${SPRING_APPLICATION_NAME_CLIENT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME_CLIENT: ${DATABASE_USERNAME_CLIENT}
      DATABASE_PASSWORD_CLIENT: ${DATABASE_PASSWORD_CLIENT}
      JPA_HIBERNATE_DDL_AUTO: ${JPA_HIBERNATE_DDL_AUTO}
      CONSUL_HOST: ${CONSUL_HOST}
      CONSUL_HTTP_PORT: ${CONSUL_HTTP_PORT}
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: ${LOGGING_LEVEL_ORG_HIBERNATE_SQL}
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK}
    depends_on:
      - mysql
      - consul
  car-service:
    profiles: ["dev"]
    build:
      context: ../car
      dockerfile: Dockerfile
    container_name: devops-ms-car-service
    ports:
      - "${CAR_SERVICE_PORT}:${CAR_SERVICE_PORT}"
    networks:
      - devops-ms-net
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CAR_SERVICE_PORT: ${CAR_SERVICE_PORT}
      SPRING_APPLICATION_NAME_CAR: ${SPRING_APPLICATION_NAME_CAR}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      DATABASE_NAME_CAR: ${DATABASE_NAME_CAR}
      DATABASE_USERNAME_CAR: ${DATABASE_USERNAME_CAR}
      DATABASE_PASSWORD_CAR: ${DATABASE_PASSWORD_CAR}
      JPA_HIBERNATE_DDL_AUTO: ${JPA_HIBERNATE_DDL_AUTO}
      CONSUL_HOST: ${CONSUL_HOST}
      CONSUL_HTTP_PORT: ${CONSUL_HTTP_PORT}
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: ${LOGGING_LEVEL_ORG_HIBERNATE_SQL}
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK}
    depends_on:
      - mysql
      - consul
  eureka:
    profiles: ["infra", "dev"]
    build:
      context: ../eureka
      dockerfile: Dockerfile
      target: dev
    image: devops-ms-eureka:latest
    container_name: devops-ms-eureka
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    networks:
      - devops-ms-net
    environment:
      EUREKA_APPLICATION_NAME: ${EUREKA_APPLICATION_NAME}
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
      EUREKA_INSTANCE_HOSTNAME: ${EUREKA_INSTANCE_HOSTNAME}
  gateway:
    profiles: ["dev"]
    build:
      context: ../gateway
      dockerfile: Dockerfile
    container_name: devops-ms-gateway-service
    ports:
      - "${GATEWAY_SERVICE_PORT:-8888}:${GATEWAY_SERVICE_PORT:-8888}"
    networks:
      - devops-ms-net
    environment:
      SPRING_PROFILES_ACTIVE: docker
      GATEWAY_SERVICE_PORT: ${GATEWAY_SERVICE_PORT}
      SPRING_APPLICATION_NAME_GATEWAY: ${SPRING_APPLICATION_NAME_GATEWAY}
      CONSUL_HOST: ${CONSUL_HOST}
      CONSUL_HTTP_PORT: ${CONSUL_HTTP_PORT}
      GATEWAY_ALLOWED_ORIGINS: ${GATEWAY_ALLOWED_ORIGINS}
      GATEWAY_ALLOWED_METHODS: ${GATEWAY_ALLOWED_METHODS}
      GATEWAY_ALLOWED_HEADERS: ${GATEWAY_ALLOWED_HEADERS}
      GATEWAY_CORS_MAX_AGE: ${GATEWAY_CORS_MAX_AGE}
    depends_on:
      - consul
      - client-service
      - car-service
volumes:
  devops-ms-mysql:
  devops-ms-consul:
networks:
  devops-ms-net:
    driver: bridge