volumes:
  devops-ms-mysql:
networks:
  devops-ms-net:
    driver: bridge
services:
  mysql:
    profiles: ["infra", "dev"]
    image: mysql:latest
    container_name: devops-ms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - devops-ms-mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${MYSQL_PORT}:${MYSQL_INTERNAL_PORT}"
    networks:
      - devops-ms-net
  client-service:
    profiles: ["dev"]
    build:
      context: ../client
      dockerfile: Dockerfile
      target: dev
    image: devops-ms-client-service:latest
    container_name: devops-ms-client-service
    ports:
      - "${CLIENT_SERVICE_PORT}:${CLIENT_SERVICE_PORT}"
    networks:
      - devops-ms-net
    environment:
      CLIENT_SERVICE_PORT: ${CLIENT_SERVICE_PORT}
      SPRING_APPLICATION_NAME_CLIENT: ${SPRING_APPLICATION_NAME_CLIENT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME_CLIENT: ${DATABASE_USERNAME_CLIENT}
      DATABASE_PASSWORD_CLIENT: ${DATABASE_PASSWORD_CLIENT}
      JPA_HIBERNATE_DDL_AUTO: ${JPA_HIBERNATE_DDL_AUTO}
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: ${LOGGING_LEVEL_ORG_HIBERNATE_SQL}
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK}
      EUREKA_INSTANCE_HOSTNAME: ${EUREKA_INSTANCE_HOSTNAME}
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
    depends_on:
      - mysql
      - eureka
  car-service:
    profiles: ["dev"]
    build:
      context: ../car
      dockerfile: Dockerfile
      target: dev
    image: devops-ms-car-service:latest
    container_name: devops-ms-car-service
    ports:
      - "${CAR_SERVICE_PORT}:${CAR_SERVICE_PORT}"
    networks:
      - devops-ms-net
    environment:
      CAR_SERVICE_PORT: ${CAR_SERVICE_PORT}
      SPRING_APPLICATION_NAME_CAR: ${SPRING_APPLICATION_NAME_CAR}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      DATABASE_NAME_CAR: ${DATABASE_NAME_CAR}
      DATABASE_USERNAME_CAR: ${DATABASE_USERNAME_CAR}
      DATABASE_PASSWORD_CAR: ${DATABASE_PASSWORD_CAR}
      JPA_HIBERNATE_DDL_AUTO: ${JPA_HIBERNATE_DDL_AUTO}
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: ${LOGGING_LEVEL_ORG_HIBERNATE_SQL}
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK}
      EUREKA_INSTANCE_HOSTNAME: ${EUREKA_INSTANCE_HOSTNAME}
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
    depends_on:
      - mysql
      - eureka
  eureka:
    profiles: ["infra", "dev"]
    build:
      context: ../eureka
      dockerfile: Dockerfile
      target: dev
    image: devops-ms-eureka:latest
    container_name: devops-ms-eureka
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    networks:
      - devops-ms-net
    environment:
      EUREKA_APPLICATION_NAME: ${EUREKA_APPLICATION_NAME}
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
      EUREKA_INSTANCE_HOSTNAME: ${EUREKA_INSTANCE_HOSTNAME}
  gateway:
    profiles: ["dev"]
    build:
      context: ../gateway
      dockerfile: Dockerfile
      target: dev
    image: devops-ms-gateway-service:latest
    container_name: devops-ms-gateway-service
    ports:
      - "${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}"
    networks:
      - devops-ms-net
    environment:
      GATEWAY_SERVICE_PORT: ${GATEWAY_SERVICE_PORT}
      SPRING_APPLICATION_NAME_GATEWAY: ${SPRING_APPLICATION_NAME_GATEWAY}
      GATEWAY_ALLOWED_ORIGINS: ${GATEWAY_ALLOWED_ORIGINS}
      GATEWAY_ALLOWED_METHODS: ${GATEWAY_ALLOWED_METHODS}
      GATEWAY_ALLOWED_HEADERS: ${GATEWAY_ALLOWED_HEADERS}
      GATEWAY_CORS_MAX_AGE: ${GATEWAY_CORS_MAX_AGE}
      EUREKA_INSTANCE_HOSTNAME: ${EUREKA_INSTANCE_HOSTNAME}
      EUREKA_SERVER_PORT: ${EUREKA_SERVER_PORT}
    depends_on:
      - client-service
      - car-service
      - eureka

  web-dev:
    profiles: ["dev"]
    build:
      context: ../web
      target: dev
    image: devop-ms-web:latest
    container_name: devops-ms-web
    ports:
      - "5173:5173"
    volumes:
      - ../web:/app
      - /app/node_modules
    environment:
      - VITE_DEV_SERVER=true
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    networks:
      - devops-ms-net
    depends_on:
      - eureka
      - gateway

  web-prod:
    profiles: ['prod']
    build:
      context: .
      target: prod 
    ports:
      - "8080:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
version: "3.9"
