spring:
  config:
    activate:
      on-profile:
      - prod
  application:
    name: ${EUREKA_APPLICATION_NAME}

server:
  port: ${EUREKA_SERVER_PORT}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME}:${server.port}/eureka/
