server:
  port: ${CAR_SERVICE_PORT}

spring:
  config:
    activate:
      on-profile:
      - prod
  application:
    name: ${SPRING_APPLICATION_NAME_CAR}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DATABASE_NAME_CAR}?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME_CAR}
    password: ${DATABASE_PASSWORD_CAR}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:create}
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.hibernate.SQL: ${LOGGING_LEVEL_ORG_HIBERNATE_SQL:DEBUG}
    org.springframework: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK:INFO}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    appname: ${spring.application.name}