server:
  port: ${CLIENT_SERVICE_PORT}

spring:
  config:
    activate:
      on-profile:
      - prod
  application:
    name: ${SPRING_APPLICATION_NAME_CLIENT}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DATABASE_NAME}?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME_CLIENT}
    password: ${DATABASE_PASSWORD_CLIENT}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.hibernate.SQL: ${LOGGING_LEVEL_ORG_HIBERNATE_SQL}
    org.springframework: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK}

eureka:
  client:
    service-url:
      # defaultZone: http://${EUREKA_INSTANCE_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka/
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    appname: ${spring.application.name}