server:
  port: ${CLIENT_SERVICE_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME_CLIENT}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DATABASE_NAME}?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME_CLIENT}
    password: ${DATABASE_PASSWORD_CLIENT}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_HTTP_PORT}
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
      config:
        enabled: false
        format: yaml
        default-context: application
        profile-separator: "-"
management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.hibernate.SQL: ${LOGGING_LEVEL_ORG_HIBERNATE_SQL}
    org.springframework: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK}